# Generated by Django 5.0.6 on 2025-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_organizer_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
