# Generated by Django 5.0.6 on 2025-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_created_at_project_volunteers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills_required',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_commitment',
            field=models.IntegerField(),
        ),
    ]
