# Generated by Django 5.0.6 on 2025-01-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_volunteer_is_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='organization_name',
        ),
    ]
