# Generated by Django 5.0.6 on 2025-02-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_volunteer_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='request_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
