# Generated by Django 5.0.6 on 2025-01-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
