# Generated by Django 5.0.6 on 2025-02-17 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipation',
            name='participation_type',
            field=models.CharField(choices=[('attending', 'Attending'), ('volunteering', 'Volunteering')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipation',
            unique_together={('user', 'project')},
        ),
    ]
