# Generated by Django 5.0.6 on 2025-02-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_event_volunteers_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
